services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: championsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - "3333:3306"